dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "oUEHkOeRXBE5qpWMP9zcPvFE6r+AvUmmDdWcUYHSsFSFFUsP5te9UuBVayu6+ypxiV6gFwOWamtoBAweWt2ePQHR4
UqKZcyVdLIvltFFJTB1W73wEXHd+fYQTWVc5KydiFSaUxEkLyJbVWjkt4CbI3MR7MpVpsleulFdsAxSgWauIBHpJN0JVAVdUohLk
+6RnQIEqDcfRfrwuzthedVJDv8nqtDGdWL4Z0lVgngKorZCUqJ63myowMC2bXcSKz/ui2Xxd6blZXj+JJ2SPWLrzrJorTXj6lP+G
+zaWOJ6/imyN1N6NNErt9JM4/5v7z9CfTCh1yALKZ6MsMA9koSHzYzp26UhJeEoRLO67QZmuCxU8Fdbo1j47O31WKkT9JBO8LMFQ
8EYonU4SMDDt54ytR8bn9Uz56SM5WMu2jd9RQkt8YqwwvtmumWepGtwroJiOfy2mq06OKY5bQVLtqvpD4CjqVcQ2Q3Q49O8f+COH
Rhw5uJfu8yezfP72WSqyZ7TOccUW7LNHgdMQrPyS7ruq21nPfge/4cN1JJF5WvnJ9SyBlGcSsuyIKClmhzUGszsOloLBS8Vane2K
Cu34TJGDtbpqbFNWi7B4dG5ASX/tjVJ/xlU3R3Wa6PlcI9k1VgdTgEb43D6dr1i64gHERXIir4Nj++8mM3X3K8OaGf7CSg="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U --settings travis-settings.xml
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage --settings travis-settings.xml
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B --settings travis-settings.xml
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B --settings travis-settings.xml
